# Generated by Django 4.0.4 on 2022-06-01 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NeuralNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nn_model', models.FileField(upload_to='models/')),
                ('x_test', models.FileField(upload_to='models/')),
                ('y_test', models.FileField(upload_to='models/')),
                ('min_value', models.FloatField()),
                ('max_value', models.FloatField()),
                ('number_of_values', models.IntegerField()),
            ],
        ),
    ]
